# Generated by Django 3.1.1 on 2020-09-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
