# Generated by Django 3.1.1 on 2020-10-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
