# Generated by Django 3.1.1 on 2020-10-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_blogpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ManyToManyField(related_name='blog_posts', to='blogapp.Category'),
        ),
    ]
