# Generated by Django 3.1.1 on 2020-10-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='url',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.IntegerField(),
        ),
    ]
